language: c

dist: xenial

git:
  depth: false

jobs:
  include:
    - stage: deploy
      name: "Packaging"
      services:
        - docker
      addons:
        apt:
          update: true
          packages:
            # required for copr-cli
            - python3-pip
      install:
        # Get the rpmbuilder
        - docker pull mgruener/rpmbuild
        # Get copr-cli
        - pip3 install --user setuptools
        - pip3 install --user --upgrade pip
        - pip3 install --user copr-cli
      script:
        # create the folder structure for RPMBUILD
        - mkdir -p $HOME/rpmbuild/SOURCES
        - mkdir -p $HOME/rpmbuild/SPECS
        - mkdir -p $HOME/rpmbuild/SRPMS
        - mkdir -p $HOME/rpmbuild/BUILD
        - mkdir -p $HOME/rpmbuild/RPMS
        - mkdir -p $HOME/rpmbuild/BUILDROOT
        - chmod -R 0777 $HOME/rpmbuild
        # create a copy of the sources for RPMBUILD
        - tar -czf $HOME/rpmbuild/SOURCES/$(git rev-parse HEAD).tar.gz .
        - cp ./packaging/SPEC/wine-nine-unstable.spec.tmpl $HOME/rpmbuild/SPECS/wine-nine-unstable.spec
        - export PATCHLEVEL=$(git rev-list --count master)
        - export COMMITHASH=$(git rev-parse HEAD)
        - export MYCHANGELOG=$(LANG=en git log --pretty=format:"* %cd %an <%ae>%n- %s%n" --date=format:"%a %b %d %Y" -n 10| sed 's/$/ \\/')
        # should use rpmbuild --define '', but whitespace and space make it difficult...
        - echo "%define patchlevel $PATCHLEVEL" > $HOME/rpmbuild/SPECS/wine-nine-unstable.spec
        - echo "%define commithash $COMMITHASH" >> $HOME/rpmbuild/SPECS/wine-nine-unstable.spec
        - echo "%define mychangelog $MYCHANGELOG" >> $HOME/rpmbuild/SPECS/wine-nine-unstable.spec
        - cat wine-nine-unstable.spec.tmpl >> $HOME/rpmbuild/SPECS/wine-nine-unstable.spec
        - sudo docker run -it --rm -v $HOME/rpmbuild/:/home/rpmbuild/rpmbuild:z mgruener/rpmbuild rpmbuild -bs --define 'dist .fc28' rpmbuild/SPECS/wine-nine-unstable.spec
        - sudo docker run -it --rm -v $HOME/rpmbuild/:/home/rpmbuild/rpmbuild:z mgruener/rpmbuild rpmbuild -bs --define 'dist .fc29' rpmbuild/SPECS/wine-nine-unstable.spec
        - copr-cli build wine-nine-unstable $HOME/rpmbuild/SRPMS/wine-nine-unstable*.src.rpm

